type token =
  | EOF
  | AUTO of (Range.t * string)
  | REGISTER of (Range.t * string)
  | STATIC of (Range.t * string)
  | EXTERN of (Range.t * string)
  | TYPEDEF of (Range.t * string)
  | VOID of (Range.t * string)
  | CHAR of (Range.t * string)
  | SHORT of (Range.t * string)
  | INT of (Range.t * string)
  | LONG of (Range.t * string)
  | FLOAT of (Range.t * string)
  | DOUBLE of (Range.t * string)
  | SIGNED of (Range.t * string)
  | UNSIGNED of (Range.t * string)
  | CONST of (Range.t * string)
  | VOLATILE of (Range.t * string)
  | STRUCT of (Range.t * string)
  | ENUM of (Range.t * string)
  | UNION of (Range.t * string)
  | LBRACE of (Range.t * string)
  | RBRACE of (Range.t * string)
  | COMMA of (Range.t * string)
  | LPAREN of (Range.t * string)
  | RPAREN of (Range.t * string)
  | LBRACKET of (Range.t * string)
  | RBRACKET of (Range.t * string)
  | STAR of (Range.t * string)
  | SEMI of (Range.t * string)
  | COLON of (Range.t * string)
  | DOT of (Range.t * string)
  | EQUALS of (Range.t * string)
  | IDENT of (Range.t * string)

val toplevel :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> string
